version: '3.1'

services:
  app:
    build: .
    volumes:
    - .:/app/
    - /app/node_modules
    env_file:
    - ~/env/respiree-backend/.env
    ports:
    - "3000:3000"
    depends_on:
    - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=davin
      - POSTGRES_PASSWORD=davin
      - POSTGRES_DB=dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always 
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres-data:
    external: true

