export enum NOTIFICATION_EVENT {
  ALERT = 'ALERT',
  INVITE = 'INVITE',
  MESSAGE = 'MESSAGE',
  REMINDER = 'REMINDER',
  NOTIFY = 'NOTIFY',
  MEDICAL_ALERT = 'MEDICAL_ALERT',
  NON_MEDICAL_ALERT = 'NON_MEDICAL_ALERT',
  CUSTOM_ALERT = 'CUSTOM_ALERT',
}

export enum ALERT_TYPE {
  AMBER_ALERT = 'AMBER_ALERT',
  RED_ALERT = 'RED_ALERT',
  GREEN_ALERT = 'GREEN_ALERT',
}

export enum CUSTOM_ALERT_TYPE {
  MEDICAL_ALERT = 'MEDICAL_ALERT',
  NON_MEDICAL_ALERT = 'NON_MEDICAL_ALERT',
}

export const NOTIFICATION_EVENTS = {
  INVITE_NEW_CARE_TEAM: {
    event: NOTIFICATION_EVENT.INVITE,
    eventType: 'CARE_TEAM',
    eventName: 'NEW_CARE_TEAM',
  },
  INVITE_NEW_APPOINTMENT: {
    event: NOTIFICATION_EVENT.INVITE,
    eventType: 'APPOINTMENT',
    eventName: 'NEW_APPOINTMENT',
  },
  SCHEDULED_APPOINTMENT_FOR_DOCTOR: {
    event: NOTIFICATION_EVENT.NOTIFY,
    eventType: 'APPOINTMENT',
    eventName: 'SCHEDULED_APPOINTMENT_FOR_DOCTOR',
  },
  APPOINTMENT_CONFIRMATION_TO_ALL: {
    event: NOTIFICATION_EVENT.NOTIFY,
    eventType: 'APPOINTMENT',
    eventName: 'APPOINTMENT_CONFIRMATION',
  },
  APPOINTMENT_CANCELLATION_TO_ALL: {
    event: NOTIFICATION_EVENT.NOTIFY,
    eventType: 'APPOINTMENT',
    eventName: 'APPOINTMENT_CANCELLATION',
  },
  APPOINTMENT_REJECTION: {
    event: NOTIFICATION_EVENT.NOTIFY,
    eventType: 'APPOINTMENT',
    eventName: 'APPOINTMENT_REJECTION',
  },
  NOTIFY_JOIN_VIDEO_CALL_APPOINTMENT: {
    event: NOTIFICATION_EVENT.NOTIFY,
    eventType: 'APPOINTMENT',
    eventName: 'JOIN_VIDEO_CALL',
  },
  NOTIFY_CLINICIAN_NOTE_PATIENT: {
    event: NOTIFICATION_EVENT.NOTIFY,
    eventType: 'NOTES',
    eventName: 'CLINICIAN_NOTE_PATIENT',
  },
  NEW_DIRECT_CHAT_MESSAGE: {
    event: NOTIFICATION_EVENT.MESSAGE,
    eventType: 'DIRECT_MESSAGE',
    eventName: 'NEW_DIRECT_MESSAGE',
  },
  APPOINTMENT_USERS_REMINDER: {
    event: NOTIFICATION_EVENT.REMINDER,
    eventType: 'APPOINTMENT',
    eventName: 'APPOINTMENT_USERS',
  },
  APPOINTMENT_DOCTOR_REMINDER: {
    event: NOTIFICATION_EVENT.REMINDER,
    eventType: 'APPOINTMENT',
    eventName: 'APPOINTMENT_DOCTOR',
  },
  DEFAULT_MEDICATION_REMINDER: {
    event: NOTIFICATION_EVENT.REMINDER,
    eventType: 'COMPLIANCE',
    eventName: 'DEFAULT_MEDICATION',
  },
  CUSTOM_MEDICATION_REMINDER: {
    event: NOTIFICATION_EVENT.REMINDER,
    eventType: 'COMPLIANCE',
    eventName: 'CUSTOM_MEDICATION',
  },
  DEFAULT_BREATHING_EXERCISE_REMINDER: {
    event: NOTIFICATION_EVENT.REMINDER,
    eventType: 'COMPLIANCE',
    eventName: 'DEFAULT_BREATHING_EXERCISE',
  },
  CUSTOM_BREATHING_EXERCISE_REMINDER: {
    event: NOTIFICATION_EVENT.REMINDER,
    eventType: 'COMPLIANCE',
    eventName: 'CUSTOM_BREATHING_EXERCISE',
  },
  SENSOR_USE_REMINDER: {
    event: NOTIFICATION_EVENT.REMINDER,
    eventType: 'COMPLIANCE',
    eventName: 'USE_OF_SENSOR',
  },
  HEALTH_INPUT_REMINDER: {
    event: NOTIFICATION_EVENT.REMINDER,
    eventType: 'COMPLIANCE',
    eventName: 'SYMPTOMS_QUESTIONNAIR',
  },
  AMBER_ALERT_PATIENT: {
    event: NOTIFICATION_EVENT.ALERT,
    eventType: ALERT_TYPE.AMBER_ALERT,
    eventName: 'AMBER_ALERT_PATIENT',
  },
  RED_ALERT_PATIENT: {
    event: NOTIFICATION_EVENT.ALERT,
    eventType: ALERT_TYPE.RED_ALERT,
    eventName: 'RED_ALERT_PATIENT',
  },
  AMBER_ALERT_CLINICIAN: {
    event: NOTIFICATION_EVENT.ALERT,
    eventType: ALERT_TYPE.AMBER_ALERT,
    eventName: 'AMBER_ALERT_CLINICIAN',
  },
  RED_ALERT_CLINICIAN: {
    event: NOTIFICATION_EVENT.ALERT,
    eventType: ALERT_TYPE.RED_ALERT,
    eventName: 'RED_ALERT_CLINICIAN',
  },
  AMBER_ALERT_CAREGIVER: {
    event: NOTIFICATION_EVENT.ALERT,
    eventType: ALERT_TYPE.AMBER_ALERT,
    eventName: 'AMBER_ALERT_CAREGIVER',
  },
  RED_ALERT_CAREGIVER: {
    event: NOTIFICATION_EVENT.ALERT,
    eventType: ALERT_TYPE.RED_ALERT,
    eventName: 'RED_ALERT_CAREGIVER',
  },
  CUSTOM_MEDICAL_ALERT_PATIENT: {
    event: NOTIFICATION_EVENT.CUSTOM_ALERT,
    eventType: CUSTOM_ALERT_TYPE.MEDICAL_ALERT,
    eventName: 'CUSTOM_MEDICAL_ALERT_PATIENT',
  },
  CUSTOM_NON_MEDICAL_ALERT_PATIENT: {
    event: NOTIFICATION_EVENT.CUSTOM_ALERT,
    eventType: CUSTOM_ALERT_TYPE.NON_MEDICAL_ALERT,
    eventName: 'CUSTOM_NON_MEDICAL_ALERT_PATIENT',
  },
  AMBER_MEDICAL_ALERT_PATIENT: {
    event: NOTIFICATION_EVENT.MEDICAL_ALERT,
    eventType: ALERT_TYPE.AMBER_ALERT,
    eventName: 'AMBER_MEDICAL_ALERT_PATIENT',
  },
  RED_MEDICAL_ALERT_PATIENT: {
    event: NOTIFICATION_EVENT.MEDICAL_ALERT,
    eventType: ALERT_TYPE.RED_ALERT,
    eventName: 'RED_MEDICAL_ALERT_PATIENT',
  },
  GREEN_MEDICAL_ALERT_PATIENT: {
    event: NOTIFICATION_EVENT.MEDICAL_ALERT,
    eventType: ALERT_TYPE.GREEN_ALERT,
    eventName: 'GREEN_MEDICAL_ALERT_PATIENT',
  },
  NON_MEDICAL_NOTIFICATION_EVENT: {
    event: NOTIFICATION_EVENT.NON_MEDICAL_ALERT,
    eventType: 'ORGANIZATION_ALERT',
    eventName: 'NON_MEDICAL_ORGANIZATION_ALERT',
  },
};

export const EVENT_SCHEDULERS = {
  SCHEDULER_JOBS: {
    ENABLE: 'ENABLE_JOB',
    DISABLE: 'DISABLE_JOB',
    DELETE: 'DELETE_JOB',
  },
  SCHEDULED_REMINDER: {
    CREATE: 'CREATE_SCHEDULED_REMINDER',
    UPDATE: 'UPDATE_SCHEDULED_REMINDER',
    DELETE: 'DELETE_REMINDER',
  },
  DAILY_REMINDER: {
    CREATE: 'CREATE_DAILY_REMINDER',
    UPDATE: 'UPDATE_DAILY_REMINDER',
    DELETE: 'DELETE_REMINDER',
  },
  DAILY_DEFAULT_REMINDER: {
    CREATE: 'CREATE_DAILY_DEFAULT_REMINDER',
    UPDATE: 'UPDATE_DAILY_DEFAULT_REMINDER',
    DELETE: 'DELETE_DAILY_DEFAULT_REMINDER',
  },
  INTERVAL_JOBS: {
    CREATE: 'CREATE_INTERVAL_JOB',
    UPDATE: 'UPDATE_INTERVAL_JOB',
    DELETE: 'DELETE_JOB',
  },
};

export enum DATA_SERVER_PATIENT_ALERTS {
  COMPLIANCE_SCORE = 'compliance_score',
  SENSOR_DAYS_MISSED = 'sensor_days_missed',
  DECOMPENSATION_SCORE = 'decompensation_score',
  EWS_SCORE = 'ews_score',
  HEART_RATE_LOWER_THAN = 'heart_rate_lower_than',
  HEART_RATE_HIGHER_THAN = 'heart_rate_higher_than',
  RESPIRATION_RATE_LOWER_THAN = 'respiration_rate_lower_than',
  RESPIRATION_RATE_HIGHER_THAN = 'respiration_rate_higher_than',
  TEMPERATURE = 'temperature',
  SPO2 = 'spo2',
  ACTIVITY_SCORE = 'activity_score',
  BLOOD_PRESSURE_SYSTOLIC_LOWER_THAN = 'blood_pressure_systolic_lower_than',
  BLOOD_PRESSURE_SYSTOLIC_HIGHER_THAN = 'blood_pressure_systolic_higher_than',
  BLOOD_PRESSURE_DIASTOLIC_LOWER_THAN = 'blood_pressure_diastolic_lower_than',
  BLOOD_PRESSURE_DIASTOLIC_HIGHER_THAN = 'blood_pressure_diastolic_higher_than',
}
export enum APP_SERVER_PATIENT_ALERTS {
  PATIENT_NOTES = 'patient_notes',
  MEDICATION_DAYS_MISSED = 'medication_days_missed',
  BREATHING_EXERCISE_DAYS_MISSED = 'breathing_exercise_days_missed',
  SENSOR_DAYS_MISSED = 'sensor_days_missed',
  HEALTH_INPUTS_DAYS_MISSED = 'health_inputs_days_missed',
  SYMPTOMS_DAYS_MISSED = 'symptoms_days_missed',
  SYMPTOMS_SCORE = 'symptoms_score',
}

export enum PATIENT_PRESCRIPTION_BASED_INPUTS {
  MEDICATION_INPUT = 'medication_input',
  BREATHING_INPUT = 'breathing_input',
}

export enum PATIENT_DAILY_BASED_INPUTS {
  HEALTH_INPUT = 'health_input',
  SYMPTOMS_INPUT = 'symptoms_input',
}

export enum CONSTANT_KEYS {
  REGISTRATION_CODE = 'REGISTRATION_VERIFY_CODE',
}
